### ISSUE TITLE
Search results ordering is sub-optimal

### ISSUE THREAD

**Issue by chancez** [cilium/cilium.io#200]
We should show newer blogs ahead of older ones.

Currently, when searching “cilium release” I see: 1.12 release, then 0.10, then 1.7, service mesh beta, 0.9, kafka, 1.0.0-rc4. Ideally, newer releases should come first in that list.

Screenshot:
![Screenshot 2022-11-22 at 2 54 01 PM](https://user-images.githubusercontent.com/1400401/204337791-c0008e8f-af15-4210-b31d-886d4d0c21bd.png)

**Comment by kayceeDev** [comment]
@chancez I will love to take up this issue.

**Comment by chancez** [comment]
Feel free to give it a try, I'm not sure what it involves.

**Comment by amRohitKumar** [comment]
@chancez  could you please specify which search box you are referring to? Are you talking about the one on the blog page?

**Comment by chancez** [comment]
It's been a while, but yes, it looks to be on the blog side of things. https://cilium.io/blog/

**Comment by amRohitKumar** [comment]
@chancez 
After reviewing the repository and consulting the Algolia documentation, I have discovered that in order to sort the search results based on a specific attribute, it is necessary to create a rule within the 'Ranking and Sorting' section. I have attached screenshots of the website for your convenience.

![image](https://github.com/cilium/cilium.io/assets/78253058/083e5376-1a28-464d-b057-ef412953bea0)
>Configuration>Ranking and Sorting>Add sort by attribute

**Comment by xmulligan** [comment]
<img width="1279" alt="Screenshot 2023-12-15 at 16 11 18" src="https://github.com/cilium/cilium.io/assets/29048870/861288d8-763f-4887-9bb6-44667d9c4b63">
there is a release tag so I'm going to close this for now. Feel free to reopen if you find something else
